import type { 
  Project, 
  Asset, 
  Campaign, 
  Message, 
  FeedbackItem, 
  TeamMember, 
  ProjectProfitability 
} from "@shared/schema";

export const dummyProjects: Project[] = [
  {
    id: "1",
    name: "Brand Refresh 2024",
    client: "TechCorp Inc.",
    icon: "🎨",
    color: "bg-blue-500",
    progress: 75,
    deadline: "Mar 15, 2024",
    team: "5",
    status: "In Progress",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "E-commerce Launch",
    client: "ShopFast",
    icon: "🛒",
    color: "bg-purple-500",
    progress: 45,
    deadline: "Apr 30, 2024",
    team: "7",
    status: "In Progress",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Social Media Campaign",
    client: "FitLife Wellness",
    icon: "📱",
    color: "bg-green-500",
    progress: 90,
    deadline: "Mar 01, 2024",
    team: "3",
    status: "In Review",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    name: "Product Photography",
    client: "Luxe Fashion",
    icon: "📸",
    color: "bg-pink-500",
    progress: 100,
    deadline: "Feb 20, 2024",
    team: "2",
    status: "Completed",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "5",
    name: "Website Redesign",
    client: "StartupHub",
    icon: "💻",
    color: "bg-orange-500",
    progress: 60,
    deadline: "May 15, 2024",
    team: "6",
    status: "In Progress",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "6",
    name: "Video Production",
    client: "GlobalTech",
    icon: "🎬",
    color: "bg-red-500",
    progress: 30,
    deadline: "Jun 01, 2024",
    team: "4",
    status: "In Progress",
    createdAt: new Date("2024-02-15"),
  },
];

export const dummyAssets: Asset[] = [
  {
    id: "1",
    name: "hero-banner-2024.jpg",
    size: "2.4 MB",
    type: "Image",
    url: "/assets/hero-banner-2024.jpg",
    thumbnail: "🖼️",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    name: "product-showcase.mp4",
    size: "45.8 MB",
    type: "Video",
    url: "/assets/product-showcase.mp4",
    thumbnail: "🎥",
    createdAt: new Date("2024-02-19"),
  },
  {
    id: "3",
    name: "logo-variations.ai",
    size: "8.1 MB",
    type: "Document",
    url: "/assets/logo-variations.ai",
    thumbnail: "📄",
    createdAt: new Date("2024-02-18"),
  },
  {
    id: "4",
    name: "3d-product-model.blend",
    size: "124.5 MB",
    type: "3D Model",
    url: "/assets/3d-product-model.blend",
    thumbnail: "🎲",
    createdAt: new Date("2024-02-17"),
  },
  {
    id: "5",
    name: "brand-guidelines.pdf",
    size: "3.2 MB",
    type: "Document",
    url: "/assets/brand-guidelines.pdf",
    thumbnail: "📋",
    createdAt: new Date("2024-02-16"),
  },
  {
    id: "6",
    name: "social-media-graphics.psd",
    size: "15.7 MB",
    type: "Image",
    url: "/assets/social-media-graphics.psd",
    thumbnail: "🎨",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "7",
    name: "promo-video-final.mov",
    size: "78.3 MB",
    type: "Video",
    url: "/assets/promo-video-final.mov",
    thumbnail: "📹",
    createdAt: new Date("2024-02-14"),
  },
  {
    id: "8",
    name: "mockup-designs.fig",
    size: "6.9 MB",
    type: "Document",
    url: "/assets/mockup-designs.fig",
    thumbnail: "🎯",
    createdAt: new Date("2024-02-13"),
  },
];

export const dummyCampaigns: Campaign[] = [
  {
    id: "1",
    name: "Spring Collection Launch",
    platform: "Instagram",
    icon: "📷",
    color: "bg-gradient-to-br from-purple-500 to-pink-500",
    status: "Active",
    impressions: "234.5K",
    clicks: "12.8K",
    ctr: "5.4%",
    spend: "$2,840",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "2",
    name: "Product Demo Series",
    platform: "YouTube",
    icon: "▶️",
    color: "bg-gradient-to-br from-red-500 to-orange-500",
    status: "Active",
    impressions: "487.2K",
    clicks: "28.4K",
    ctr: "5.8%",
    spend: "$4,120",
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "3",
    name: "Brand Awareness Q1",
    platform: "Facebook",
    icon: "👍",
    color: "bg-gradient-to-br from-blue-500 to-blue-600",
    status: "Active",
    impressions: "892.1K",
    clicks: "45.2K",
    ctr: "5.1%",
    spend: "$6,750",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    name: "Flash Sale Campaign",
    platform: "TikTok",
    icon: "🎵",
    color: "bg-gradient-to-br from-cyan-400 to-pink-500",
    status: "Scheduled",
    impressions: "0",
    clicks: "0",
    ctr: "0%",
    spend: "$0",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "5",
    name: "Professional Network",
    platform: "LinkedIn",
    icon: "💼",
    color: "bg-gradient-to-br from-blue-700 to-blue-800",
    status: "Active",
    impressions: "156.7K",
    clicks: "8.9K",
    ctr: "5.7%",
    spend: "$3,200",
    createdAt: new Date("2024-02-05"),
  },
];

export const dummyMessages: Message[] = [
  {
    id: "1",
    client: "Sarah Johnson",
    initials: "SJ",
    color: "bg-blue-500",
    project: "Brand Refresh 2024",
    content: "Love the new color palette! Can we explore a few more font options for the headers?",
    time: "2 hours ago",
    needsReview: true,
    createdAt: new Date("2024-02-20T14:30:00"),
  },
  {
    id: "2",
    client: "Michael Chen",
    initials: "MC",
    color: "bg-purple-500",
    project: "E-commerce Launch",
    content: "The homepage mockup looks fantastic. Let's schedule a call to discuss the checkout flow.",
    time: "5 hours ago",
    needsReview: false,
    createdAt: new Date("2024-02-20T11:30:00"),
  },
  {
    id: "3",
    client: "Emily Rodriguez",
    initials: "ER",
    color: "bg-green-500",
    project: "Social Media Campaign",
    content: "Great engagement on the first post! Can we adjust the posting schedule for better reach?",
    time: "1 day ago",
    needsReview: true,
    createdAt: new Date("2024-02-19T10:00:00"),
  },
  {
    id: "4",
    client: "David Park",
    initials: "DP",
    color: "bg-orange-500",
    project: "Website Redesign",
    content: "The wireframes are approved. Ready to move forward with the design phase.",
    time: "2 days ago",
    needsReview: false,
    createdAt: new Date("2024-02-18T15:20:00"),
  },
  {
    id: "5",
    client: "Lisa Thompson",
    initials: "LT",
    color: "bg-pink-500",
    project: "Product Photography",
    content: "Photos delivered are stunning! Minor retouching needed on images 12-15.",
    time: "3 days ago",
    needsReview: true,
    createdAt: new Date("2024-02-17T09:45:00"),
  },
];

export const dummyFeedbackItems: FeedbackItem[] = [
  {
    id: "1",
    title: "Logo size adjustment needed",
    client: "TechCorp Inc.",
    priority: "High",
    time: "1 hour ago",
    createdAt: new Date("2024-02-20T15:30:00"),
  },
  {
    id: "2",
    title: "Update call-to-action button color",
    client: "ShopFast",
    priority: "Medium",
    time: "4 hours ago",
    createdAt: new Date("2024-02-20T12:30:00"),
  },
  {
    id: "3",
    title: "Revise video thumbnail",
    client: "FitLife Wellness",
    priority: "Low",
    time: "6 hours ago",
    createdAt: new Date("2024-02-20T10:30:00"),
  },
  {
    id: "4",
    title: "Add product specifications section",
    client: "Luxe Fashion",
    priority: "High",
    time: "1 day ago",
    createdAt: new Date("2024-02-19T16:30:00"),
  },
  {
    id: "5",
    title: "Optimize mobile navigation",
    client: "StartupHub",
    priority: "Medium",
    time: "2 days ago",
    createdAt: new Date("2024-02-18T14:00:00"),
  },
];

export const dummyTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Alex Rivera",
    initials: "AR",
    role: "Creative Director",
    color: "bg-blue-500",
    utilization: 85,
    hours: 34,
    projects: ["Brand Refresh 2024", "Website Redesign"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Jordan Lee",
    initials: "JL",
    role: "Senior Designer",
    color: "bg-purple-500",
    utilization: 92,
    hours: 37,
    projects: ["E-commerce Launch", "Social Media Campaign", "Product Photography"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Sam Patel",
    initials: "SP",
    role: "Video Producer",
    color: "bg-green-500",
    utilization: 78,
    hours: 31,
    projects: ["Video Production", "Social Media Campaign"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "Taylor Morgan",
    initials: "TM",
    role: "UX Designer",
    color: "bg-orange-500",
    utilization: 88,
    hours: 35,
    projects: ["Website Redesign", "E-commerce Launch"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "5",
    name: "Casey Williams",
    initials: "CW",
    role: "Marketing Specialist",
    color: "bg-pink-500",
    utilization: 75,
    hours: 30,
    projects: ["Social Media Campaign"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "6",
    name: "Riley Brooks",
    initials: "RB",
    role: "3D Artist",
    color: "bg-red-500",
    utilization: 82,
    hours: 33,
    projects: ["Product Photography", "Video Production"],
    createdAt: new Date("2024-01-01"),
  },
];

export const dummyProjectProfitability: ProjectProfitability[] = [
  {
    id: "1",
    projectId: "1",
    budget: "$45,000",
    spent: "$33,750",
    hours: "340",
    revenue: "$52,000",
    roi: "1.5",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "2",
    projectId: "2",
    budget: "$68,000",
    spent: "$30,600",
    hours: "245",
    revenue: "$72,000",
    roi: "2.4",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    projectId: "3",
    budget: "$28,000",
    spent: "$25,200",
    hours: "180",
    revenue: "$35,000",
    roi: "1.4",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "4",
    projectId: "4",
    budget: "$18,000",
    spent: "$18,000",
    hours: "120",
    revenue: "$22,000",
    roi: "1.2",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "5",
    projectId: "5",
    budget: "$55,000",
    spent: "$33,000",
    hours: "280",
    revenue: "$85,000",
    roi: "2.6",
    createdAt: new Date("2024-02-20"),
  },
];

export const dummyDashboardStats = {
  activeProjects: 6,
  teamUtilization: 83,
  campaignPerformance: 94,
  clientSatisfaction: 4.7,
};
